export const tips = [
    "Break projects into smaller tasks for better progress tracking.",
    "Use deadlines to stay accountable and keep projects on schedule.",
    "Regularly review project goals to ensure alignment with objectives.",
    "Collaborate effectively by documenting key decisions and updates.",
    "Prioritize tasks based on impact and urgency to maximize efficiency.",
    "Set clear expectations for team members to avoid confusion.",
    "Track progress with visual tools like Kanban boards or Gantt charts.",
    "Schedule regular check-ins to address roadblocks early.",
    "Encourage open communication to foster teamwork and transparency.",
    "Use project templates to save time on recurring tasks.",
    "Minimize scope creep by defining project requirements clearly.",
    "Allocate resources efficiently to avoid burnout and delays.",
    "Automate repetitive tasks to improve efficiency.",
    "Keep stakeholders informed with regular project updates.",
    "Use data and analytics to improve decision-making.",
    "Create a risk management plan to anticipate potential challenges.",
    "Celebrate small wins to maintain team motivation.",
    "Limit meetings to only necessary discussions to save time.",
    "Encourage feedback loops for continuous project improvement.",
    "Always have a contingency plan for unexpected challenges.",
  ];